import Head from 'next/head';
import Table from '../components/Table';
import Layout from '../components/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-gray-700 text-3xl font-bold mb-8">Dashboard</h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 mb-16">
        <div className="rounded bg-white shadow-sm py-2 px-1 md:h-[12rem] min-h-[12rem] max-h-[12rem]"></div>
        <div className="rounded bg-white shadow-sm py-2 px-1 md:h-[12rem] min-h-[12rem] max-h-[12rem]"></div>
        <div className="rounded bg-white shadow-sm py-2 px-1 md:h-[12rem] min-h-[12rem] max-h-[12rem]"></div>
      </div>

      <Table />
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
